### ISSUE TITLE
Add an option to reset all scores in a quality profile to 0 unless the user specifies a score.

### ISSUE THREAD

**Issue by rcdailey** [rcdailey/trash-updater#10]
Right now, scores are only updated for custom formats the user specifies in their config. That means if there are scores set for CFs not in config, the score might be non-zero and untouched.

Some users may depend entirely on TrashUpdater for updating their quality profiles. In those cases, we do not want to leave unknown/untouched scores. This option will remain disabled by default to allow manual edits to quality profiles along with automated updates.

Example:

```yml
radarr:
  - custom_formats:
      - names: [MyCustomFormat]
        quality_profiles:
          - name: MyProfile
            unmatched_scores_set_to_zero: true
```
